version: '2'
services:
    datahubrepo-app:
        image: datahubrepo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://datahubrepo-mysql:3306/datahubrepo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    datahubrepo-mysql:
        extends:
            file: mysql.yml
            service: datahubrepo-mysql
